/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/403.vue')['default']
    404: typeof import('./src/components/404.vue')['default']
    500: typeof import('./src/components/500.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    MyAutoSearch: typeof import('./src/components/myAutoSearch.vue')['default']
    MyBanner: typeof import('./src/components/myBanner.vue')['default']
    MyDropDown: typeof import('./src/components/myDropDown.vue')['default']
    MyEditor: typeof import('./src/components/myEditor.vue')['default']
    MyFooter: typeof import('./src/components/myFooter.vue')['default']
    MyHeader: typeof import('./src/components/myHeader.vue')['default']
    MyHeroBackgound: typeof import('./src/components/myHeroBackgound.vue')['default']
    MyLandingPage: typeof import('./src/components/myLandingPage.vue')['default']
    MyPopoverSearch: typeof import('./src/components/myPopoverSearch.vue')['default']
    MyPrice: typeof import('./src/components/myPrice.vue')['default']
    MyShoppingCart: typeof import('./src/components/myShoppingCart.vue')['default']
    MySideBar: typeof import('./src/components/mySideBar.vue')['default']
    MyTestimony: typeof import('./src/components/myTestimony.vue')['default']
    MyToggleTheme: typeof import('./src/components/myToggleTheme.vue')['default']
    MyTransition: typeof import('./src/components/myTransition.vue')['default']
    MyUnkownError: typeof import('./src/components/myUnkownError.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
